// ─── Song Library ────────────────────────────────────────────
// 每首歌：{ id, title, artist, baseKey, playKey, capo, chords[], sections[] }
// section: { title, lines[] }
// line: 数组，每个元素 { chord?: string, lyric: string }
//   chord 为空字符串表示无和弦标注，lyric 为对应文字

const SONGS = [
  // ──────────────────────────────────────────
  {
    id: 'nanshan',
    title: '南山南',
    artist: '马頔',
    baseKey: 'Bb', playKey: 'G', capo: 3,
    chords: ['C','D','Bm','Em','Am','G'],
    sections: [
      { title: '主歌', lines: [
        [{ chord:'C', lyric:'你在南方的' },   { chord:'D', lyric:'艳阳里  ' },    { chord:'Bm', lyric:'大雪' }, { chord:'Em', lyric:'纷飞' }],
        [{ chord:'Am', lyric:'我在北方的寒夜里' }, { chord:'D', lyric:'四季' }, { chord:'G', lyric:'如春' }],
        [{ chord:'Am', lyric:'如果' }, { chord:'G', lyric:'天黑之前' }, { chord:'C', lyric:'来的及 ' }, { chord:'D', lyric:'我要' }, { chord:'Bm', lyric:'忘了' }, { chord:'Em', lyric:'你的眼睛' }],
        [{ chord:'Am', lyric:'穷极一生 ' }, { chord:'D', lyric:'做不完 ' }, { chord:'G', lyric:'一场梦' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'G', lyric:'她不再和' }, { chord:'D', lyric:'谁谈论' }, { chord:'Em', lyric:'相逢的孤岛  ' }, { chord:'Am', lyric:'因为' }, { chord:'D', lyric:'心里' }, { chord:'G', lyric:'早已荒无人烟' }],
        [{ chord:'G', lyric:'他的心再也' }, { chord:'D', lyric:'装不下' }, { chord:'Em', lyric:'一个家  ' }, { chord:'Am', lyric:'做一个 ' }, { chord:'D', lyric:'只对' }, { chord:'G', lyric:'自己说谎的哑巴' }],
        [{ chord:'G', lyric:'他说你 ' }, { chord:'C', lyric:'任何为人称道的' }, { chord:'D', lyric:'美丽  ' }, { chord:'Bm', lyric:'不及他' }, { chord:'Em', lyric:'第一次遇见你' }],
        [{ chord:'Am', lyric:'时光苟延残喘  ' }, { chord:'D', lyric:'无可奈何' }],
        [{ chord:'Am', lyric:'如果所有' }, { chord:'G', lyric:'土地' }, { chord:'C', lyric:'连在一起 ' }, { chord:'D', lyric:'走上一生' }, { chord:'Bm', lyric:'只为' }, { chord:'Em', lyric:'拥抱你' }],
        [{ chord:'Am', lyric:'喝醉了' }, { chord:'D', lyric:'他的梦 ' }, { chord:'G', lyric:'晚安' }],
      ]},
      { title: '间奏', lines: [
        [{ chord:'G', lyric:'他听见有人' }, { chord:'D', lyric:'唱着古老的歌  ' }, { chord:'Em', lyric:'唱着今天' }, { chord:'Am', lyric:'还在' }, { chord:'D', lyric:'远方' }, { chord:'G', lyric:'发生的' }],
        [{ chord:'G', lyric:'像在她' }, { chord:'D', lyric:'眼睛里看到的孤岛  ' }, { chord:'Em', lyric:'没有悲伤' }, { chord:'Am', lyric:'但也' }, { chord:'D', lyric:'没有' }, { chord:'G', lyric:'花朵' }],
      ]},
      { title: '尾声', lines: [
        [{ chord:'Am', lyric:'大梦初醒' }, { chord:'D', lyric:'荒唐了  ' }, { chord:'G', lyric:'一生' }],
        [{ chord:'G', lyric:'南山南  ' }, { chord:'D', lyric:'北秋悲 ' }, { chord:'Em', lyric:'南山' }, { chord:'C', lyric:'有谷堆' }],
        [{ chord:'G', lyric:'南风喃  ' }, { chord:'D', lyric:'北海北 ' }, { chord:'Em', lyric:'北海' }, { chord:'C', lyric:'有墓碑' }],
      ]},
    ],
  },

  // ──────────────────────────────────────────
  {
    id: 'anhq',
    title: '安和桥',
    artist: '宋冬野',
    baseKey: 'G', playKey: 'G', capo: 0,
    chords: ['G','D','Em','C'],
    sections: [
      { title: '主歌', lines: [
        [{ chord:'G', lyric:'让我再看你一' }, { chord:'D', lyric:'遍' }],
        [{ chord:'', lyric:'从南' }, { chord:'Em', lyric:'到北' }],
        [{ chord:'', lyric:'像是' }, { chord:'C', lyric:'被五环路' }],
        [{ chord:'D', lyric:'蒙住的' }, { chord:'G', lyric:'双眼' }],
        [{ chord:'G', lyric:'请你再讲' }, { chord:'D', lyric:'一遍' }],
        [{ chord:'', lyric:'关于' }, { chord:'Em', lyric:'那天' }],
        [{ chord:'', lyric:'抱着' }, { chord:'C', lyric:'盒子的姑娘' }],
        [{ chord:'D', lyric:'和擦汗的' }, { chord:'Em', lyric:'男人' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'', lyric:'我知' }, { chord:'C', lyric:'道 那些' }, { chord:'D', lyric:'夏天' }],
        [{ chord:'', lyric:'就像' }, { chord:'Em', lyric:'青春一样' }, { chord:'D', lyric:'回不来' }],
        [{ chord:'', lyric:'代替' }, { chord:'C', lyric:'梦想的也' }, { chord:'D', lyric:'只能是勉为' }, { chord:'G', lyric:'其难' }],
        [{ chord:'', lyric:'我知' }, { chord:'C', lyric:'道 吹过的' }, { chord:'D', lyric:'牛逼' }],
        [{ chord:'', lyric:'也会随' }, { chord:'Em', lyric:'青春一笑' }, { chord:'D', lyric:'了之' }],
        [{ chord:'', lyric:'让我' }, { chord:'C', lyric:'困在城市里' }],
        [{ chord:'', lyric:'纪念' }, { chord:'Em', lyric:'你' }],
      ]},
      { title: '主歌', lines: [
        [{ chord:'G', lyric:'让我再尝' }, { chord:'D', lyric:'一口' }],
        [{ chord:'', lyric:'秋天' }, { chord:'Em', lyric:'的酒' }],
        [{ chord:'', lyric:'一' }, { chord:'C', lyric:'直往南方' }, { chord:'D', lyric:'开' }],
        [{ chord:'', lyric:'不会' }, { chord:'G', lyric:'太久' }],
        [{ chord:'G', lyric:'让我再听' }, { chord:'D', lyric:'一遍' }],
        [{ chord:'', lyric:'最美的' }, { chord:'Em', lyric:'那一句' }],
        [{ chord:'', lyric:'你回' }, { chord:'C', lyric:'家了' }],
        [{ chord:'D', lyric:'我在等你' }, { chord:'Em', lyric:'呢' }],
      ]},
      { title: '间奏', lines: [
        [{ chord:'C', lyric:' ' }, { chord:'D', lyric:' ' }, { chord:'Em', lyric:' ' }, { chord:'D', lyric:' ' }],
        [{ chord:'C', lyric:' ' }, { chord:'D', lyric:' ' }, { chord:'Em', lyric:' ' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'', lyric:'我知' }, { chord:'C', lyric:'道 那些' }, { chord:'D', lyric:'夏天' }],
        [{ chord:'', lyric:'就像' }, { chord:'Em', lyric:'青春一样' }, { chord:'D', lyric:'回不来' }],
        [{ chord:'', lyric:'代替' }, { chord:'C', lyric:'梦想的也' }, { chord:'D', lyric:'只能是勉为' }, { chord:'G', lyric:'其难' }],
        [{ chord:'', lyric:'我知' }, { chord:'C', lyric:'道 吹过的' }, { chord:'D', lyric:'牛逼' }],
        [{ chord:'', lyric:'也会随' }, { chord:'Em', lyric:'青春一笑' }, { chord:'D', lyric:'了之' }],
        [{ chord:'', lyric:'让我' }, { chord:'C', lyric:'困在城市里' }],
        [{ chord:'', lyric:'纪念' }, { chord:'Em', lyric:'你' }],
        [{ chord:'', lyric:'我知' }, { chord:'C', lyric:'道 那些' }, { chord:'D', lyric:'夏天' }],
        [{ chord:'', lyric:'就像' }, { chord:'Em', lyric:'你一样' }, { chord:'D', lyric:'回不来' }],
        [{ chord:'', lyric:'我已' }, { chord:'C', lyric:'不会再对' }, { chord:'D', lyric:'谁' }],
        [{ chord:'', lyric:'满怀' }, { chord:'G', lyric:'期待' }],
        [{ chord:'', lyric:'我知' }, { chord:'C', lyric:'道 这个' }, { chord:'D', lyric:'世界' }],
        [{ chord:'', lyric:'每天' }, { chord:'Em', lyric:'都有太多' }, { chord:'D', lyric:'遗憾' }],
        [{ chord:'', lyric:'所以 ' }, { chord:'C', lyric:'你好 ' }],
        [{ chord:'', lyric:'再' }, { chord:'Em', lyric:'见' }],
      ]},
    ],
  },

  // ──────────────────────────────────────────
  {
    id: 'qqqg',
    title: '千千阙歌',
    artist: '张国荣 / 陈慧娴',
    baseKey: 'A', playKey: 'A', capo: 0,
    chords: ['A','C#m','Bm','E','D','F#m'],
    sections: [
      { title: '主歌一', lines: [
        [{ chord:'A', lyric:'徐徐回望曾属于' }, { chord:'C#m', lyric:'彼此的晚上' }],
        [{ chord:'Bm', lyric:'红红仍是你赠我的' }, { chord:'E', lyric:'心中艳阳' }],
        [{ chord:'A', lyric:'如流傻泪 祈望可' }, { chord:'C#m', lyric:'体恤兼见谅' }],
        [{ chord:'Bm', lyric:'明晨离别你 路也许' }, { chord:'E', lyric:'孤单得漫长' }],
      ]},
      { title: '过渡', lines: [
        [{ chord:'D', lyric:'一瞬间太多' }, { chord:'E', lyric:'东西要讲' }],
        [{ chord:'C#m', lyric:'可惜即将在' }, { chord:'F#m', lyric:'各一方' }],
        [{ chord:'Bm', lyric:'只好深深将这' }, { chord:'C#m', lyric:'刻尽凝' }, { chord:'F#m', lyric:'望' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'A', lyric:'来日纵使千千阙歌　飘于远方' }, { chord:'F#m', lyric:'我路上' }],
        [{ chord:'A', lyric:'来日纵使千千晚星　亮过今晚' }, { chord:'C#m', lyric:'月亮' }],
        [{ chord:'Bm', lyric:'都比不起这' }, { chord:'F#m', lyric:'宵美丽' }],
        [{ chord:'Bm', lyric:'都洗不清今晚' }, { chord:'F#m', lyric:'我所想' }],
        [{ chord:'Bm', lyric:'因你今晚共' }, { chord:'D', lyric:'我' }, { chord:'A', lyric:'唱' }],
      ]},
      { title: '主歌二', lines: [
        [{ chord:'A', lyric:'临行临别 才顿感' }, { chord:'C#m', lyric:'哀伤的漂亮' }],
        [{ chord:'Bm', lyric:'原来全是你 令我的' }, { chord:'E', lyric:'思忆漫长' }],
        [{ chord:'A', lyric:'何年何月 才又可' }, { chord:'C#m', lyric:'今宵一样' }],
        [{ chord:'Bm', lyric:'停留凝望里 让眼睛' }, { chord:'E', lyric:'讲彼此立场' }],
      ]},
      { title: '过渡', lines: [
        [{ chord:'D', lyric:'当某天 雨点' }, { chord:'E', lyric:'轻敲你窗' }],
        [{ chord:'C#m', lyric:'当风声吹乱' }, { chord:'F#m', lyric:'你构想' }],
        [{ chord:'Bm', lyric:'可否抽空' }, { chord:'C#m', lyric:'想这张旧模' }, { chord:'F#m', lyric:'样' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'A', lyric:'来日纵使千千阙歌　飘于远方' }, { chord:'F#m', lyric:'我路上' }],
        [{ chord:'A', lyric:'来日纵使千千晚星　亮过今晚' }, { chord:'C#m', lyric:'月亮' }],
        [{ chord:'Bm', lyric:'都比不起这' }, { chord:'F#m', lyric:'宵美丽' }],
        [{ chord:'Bm', lyric:'都洗不清今晚' }, { chord:'F#m', lyric:'我所想' }],
        [{ chord:'Bm', lyric:'因你今晚共' }, { chord:'D', lyric:'我' }, { chord:'A', lyric:'唱' }],
      ]},
      { title: '尾声', lines: [
        [{ chord:'Bm', lyric:'怎都比不起这' }, { chord:'F#m', lyric:'宵美丽' }],
        [{ chord:'Bm', lyric:'亦绝不可使我' }, { chord:'F#m', lyric:'更欣赏' }],
        [{ chord:'Bm', lyric:'因我今晚共' }, { chord:'D', lyric:'你' }, { chord:'A', lyric:'唱' }],
        [{ chord:'Bm', lyric:'因不知哪天再共' }, { chord:'D', lyric:'你' }, { chord:'A', lyric:'唱' }],
      ]},
    ],
  },

  // ──────────────────────────────────────────
  {
    id: 'hotelca',
    title: 'Hotel California',
    artist: 'Eagles',
    baseKey: 'Am', playKey: 'Am', capo: 0,
    chords: ['Am','E7','G','D','F','C','Dm','E'],
    sections: [
      { title: 'Verse I', lines: [
        [{ chord:'Am', lyric:'On a dark desert high' }, { chord:'E7', lyric:'way, cool wind in my hair' }],
        [{ chord:'G', lyric:'Warm smell of colitas ' }, { chord:'D', lyric:'rising up through the air' }],
        [{ chord:'F', lyric:'Up ahead in the distance, ' }, { chord:'C', lyric:'I saw a shimmering light' }],
        [{ chord:'Dm', lyric:'My head grew heavy and my sight grew dim' }],
        [{ chord:'E', lyric:'I had to stop for the night' }],
        [{ chord:'Am', lyric:'There she stood in the doorway; ' }, { chord:'E7', lyric:'I heard the mission bell' }],
        [{ chord:'G', lyric:'And I was thinking to myself, this could be ' }, { chord:'D', lyric:'heaven or this could be hell' }],
        [{ chord:'F', lyric:'Then she lit up a candle, ' }, { chord:'C', lyric:'and she showed me the way' }],
        [{ chord:'Dm', lyric:'There were voices down the corridor,' }],
        [{ chord:'E', lyric:'I thought I heard them say' }],
      ]},
      { title: 'Chorus', lines: [
        [{ chord:'F', lyric:'Welcome to the Hotel Cali' }, { chord:'C', lyric:'fornia' }],
        [{ chord:'E7', lyric:'Such a lovely place, ' }, { chord:'Am', lyric:'such a lovely face' }],
        [{ chord:'F', lyric:"There's plenty of room at the Hotel Cali" }, { chord:'C', lyric:'fornia' }],
        [{ chord:'Dm', lyric:'Anytime of year, ' }, { chord:'E', lyric:'you can find us here' }],
      ]},
      { title: 'Verse II', lines: [
        [{ chord:'Am', lyric:'Her mind is Tiffany twisted, ' }, { chord:'E7', lyric:'she got a Mercedes Benz' }],
        [{ chord:'G', lyric:'She got a lot of pretty pretty boys ' }, { chord:'D', lyric:'that she calls friends' }],
        [{ chord:'F', lyric:'How they danced in the courtyard, ' }, { chord:'C', lyric:'sweet summer sweat' }],
        [{ chord:'Dm', lyric:'Some dance to remember, ' }, { chord:'E', lyric:'some dance to forget' }],
        [{ chord:'Am', lyric:'So I called up the captain; ' }, { chord:'E7', lyric:'please bring me my wine' }],
        [{ chord:'G', lyric:"We haven't had that spirit here since " }, { chord:'D', lyric:'1969' }],
        [{ chord:'F', lyric:'And still those voices are calling from ' }, { chord:'C', lyric:'far away' }],
        [{ chord:'Dm', lyric:'Wake you up in the middle of the night' }],
        [{ chord:'E', lyric:'Just to hear them say' }],
      ]},
      { title: 'Chorus', lines: [
        [{ chord:'F', lyric:'Welcome to the Hotel Cali' }, { chord:'C', lyric:'fornia' }],
        [{ chord:'E7', lyric:'Such a lovely place, ' }, { chord:'Am', lyric:'such a lovely face' }],
        [{ chord:'F', lyric:"There's plenty of room at the Hotel Cali" }, { chord:'C', lyric:'fornia' }],
        [{ chord:'Dm', lyric:'Anytime of year, ' }, { chord:'E', lyric:'you can find us here' }],
      ]},
      { title: 'Verse III', lines: [
        [{ chord:'Am', lyric:'Mirrors on the ceiling, ' }, { chord:'E7', lyric:'the pink champagne on ice' }],
        [{ chord:'G', lyric:'We are all just prisoners here, ' }, { chord:'D', lyric:'of our own device' }],
        [{ chord:'F', lyric:"And in the master's chambers, " }, { chord:'C', lyric:'they gathered for the feast' }],
        [{ chord:'Dm', lyric:"They stab it with their steely knives but" }],
        [{ chord:'E', lyric:"they just can't kill the beast" }],
        [{ chord:'Am', lyric:'Last thing I remember, ' }, { chord:'E7', lyric:'I was running for the door' }],
        [{ chord:'G', lyric:'I had to find the passage back to the ' }, { chord:'D', lyric:'place I was before' }],
        [{ chord:'F', lyric:'"Relax," said the night man, ' }, { chord:'C', lyric:'we are programmed to receive' }],
        [{ chord:'Dm', lyric:'You can check out anytime you like' }],
        [{ chord:'E', lyric:'but you can never leave' }],
      ]},
    ],
  },
  // ──────────────────────────────────────────
  {
    id: 'chengdu',
    title: '成都',
    artist: '赵雷',
    baseKey: 'D', playKey: 'C', capo: 2,
    chords: ['C','Em','F','G','Am','Dm'],
    sections: [
      { title: '主歌', lines: [
        [{ chord:'C', lyric:'让我掉下眼泪的' }, { chord:'Em', lyric:'不止昨夜的酒' }],
        [{ chord:'F', lyric:'让我依依不舍的' }, { chord:'G', lyric:'不止你的温柔' }],
        [{ chord:'Em', lyric:'余路还要走多久' }, { chord:'Am', lyric:'你攥着我的手' }],
        [{ chord:'F', lyric:'让我感到为难的' }, { chord:'G', lyric:'是挣扎的' }, { chord:'C', lyric:'自由' }],
        [{ chord:'C', lyric:'分别总是在九月' }, { chord:'Em', lyric:'回忆是思念的愁' }],
        [{ chord:'F', lyric:'深秋嫩绿的垂柳' }, { chord:'G', lyric:'亲吻着我额头' }],
        [{ chord:'Em', lyric:'在那座阴雨的小城里' }, { chord:'Am', lyric:'我从未忘记你' }],
        [{ chord:'Em', lyric:'成都  ' }, { chord:'F', lyric:'带不走的' }, { chord:'C', lyric:'只有你' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'Em', lyric:'和我在成都的街头走一走' }, { chord:'Am', lyric:'哦哦' }],
        [{ chord:'F', lyric:'直到所有的灯都熄灭了' }, { chord:'G', lyric:'也不停' }, { chord:'C', lyric:'留' }],
        [{ chord:'F', lyric:'你会挽着我的衣袖' }, { chord:'G', lyric:'我会把手揣进' }, { chord:'C', lyric:'裤兜' }],
        [{ chord:'Dm', lyric:'走到玉林路的尽头' }, { chord:'G', lyric:'坐在小酒馆的门' }, { chord:'C', lyric:'口' }],
      ]},
      { title: '主歌', lines: [
        [{ chord:'C', lyric:'分别总是在九月' }, { chord:'Em', lyric:'回忆是思念的愁' }],
        [{ chord:'F', lyric:'深秋嫩绿的垂柳' }, { chord:'G', lyric:'亲吻着我额头' }],
        [{ chord:'Em', lyric:'在那座阴雨的小城里' }, { chord:'Am', lyric:'我从未忘记你' }],
        [{ chord:'Em', lyric:'成都  ' }, { chord:'F', lyric:'带不走的' }, { chord:'C', lyric:'只有你' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'Em', lyric:'和我在成都的街头走一走' }, { chord:'Am', lyric:'哦哦' }],
        [{ chord:'F', lyric:'直到所有的灯都熄灭了' }, { chord:'G', lyric:'也不停' }, { chord:'C', lyric:'留' }],
        [{ chord:'F', lyric:'你会挽着我的衣袖' }, { chord:'G', lyric:'我会把手揣进' }, { chord:'C', lyric:'裤兜' }],
        [{ chord:'Dm', lyric:'走到玉林路的尽头' }, { chord:'G', lyric:'坐在小酒馆的门' }, { chord:'C', lyric:'口' }],
        [{ chord:'Em', lyric:'和我在成都的街头走一走' }, { chord:'Am', lyric:'哦哦' }],
        [{ chord:'F', lyric:'直到所有的灯都熄灭了' }, { chord:'G', lyric:'也不停' }, { chord:'C', lyric:'留' }],
        [{ chord:'F', lyric:'你会挽着我的衣袖' }, { chord:'G', lyric:'我会把手揣进' }, { chord:'C', lyric:'裤兜' }],
        [{ chord:'Dm', lyric:'走到玉林路的尽头' }, { chord:'G', lyric:'坐在小酒馆的门' }, { chord:'C', lyric:'口' }],
      ]},
    ],
  },
  // ──────────────────────────────────────────
  {
    id: 'qinaioxiaohai',
    title: '亲爱的小孩',
    artist: '小男孩乐团',
    baseKey: 'Cm', playKey: 'Am', capo: 3,
    chords: ['Am','F','C','G'],
    sections: [
      { title: '主歌一', lines: [
        [{ chord:'Am', lyric:'哈啰 MY DEAR DARLING 你静静的睡' }, { chord:'F', lyric:'' }],
        [{ chord:'C', lyric:'享受难得片刻平安香甜' }, { chord:'G', lyric:'' }],
        [{ chord:'Am', lyric:'SORRY　让你诞生的这个世界' }, { chord:'F', lyric:'' }],
        [{ chord:'C', lyric:'危险侵略' }, { chord:'G', lyric:'残缺' }],
        [{ chord:'Am', lyric:'天不再蓝　虚耗食安' }, { chord:'F', lyric:'' }],
        [{ chord:'C', lyric:'雨森林　不再是我们神秘乐园' }, { chord:'G', lyric:'' }],
        [{ chord:'Am', lyric:'恶疾扩散　残暴战乱' }, { chord:'F', lyric:'' }],
        [{ chord:'C', lyric:'被推上　性别思想信仰批判场' }],
        [{ chord:'G', lyric:'脸孔皮肤颜色伸展台' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'C', lyric:'哎　孤立乱世　' }, { chord:'G', lyric:'拥你入怀' }, { chord:'Am', lyric:'' }],
        [{ chord:'F', lyric:'闭上眼　请牢记　这永恒' }],
        [{ chord:'C', lyric:'爱　末日曙光　' }, { chord:'G', lyric:'天际沧海' }, { chord:'Am', lyric:'' }],
        [{ chord:'F', lyric:'握紧我　冲破这　自私' }, { chord:'G', lyric:'年代' }],
        [{ chord:'F', lyric:'如果能够寻回　千年依赖' }, { chord:'C', lyric:'' }],
      ]},
      { title: '主歌二', lines: [
        [{ chord:'Am', lyric:'请保持这纯真明亮双眼' }, { chord:'F', lyric:'' }],
        [{ chord:'C', lyric:'看透融化一切邪恶假面' }, { chord:'G', lyric:'' }],
        [{ chord:'Am', lyric:'还要在　锻炼那　坚定独立思维' }, { chord:'F', lyric:'' }],
        [{ chord:'C', lyric:'勇敢面对' }, { chord:'G', lyric:'试炼' }],
        [{ chord:'Am', lyric:'政治烟硝　世界续不安' }, { chord:'F', lyric:'' }],
        [{ chord:'C', lyric:'和平钟　如履薄冰　片刻掩埋' }, { chord:'G', lyric:'' }],
        [{ chord:'Am', lyric:'压力多元　欢笑已不在' }, { chord:'F', lyric:'' }],
        [{ chord:'C', lyric:'童年竟　成为竞争奔跑补习班' }],
        [{ chord:'G', lyric:'无尽功课晚餐到夜半' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'C', lyric:'哎　孤立乱世　' }, { chord:'G', lyric:'拥你入怀' }, { chord:'Am', lyric:'' }],
        [{ chord:'F', lyric:'闭上眼　请牢记　这永恒' }],
        [{ chord:'C', lyric:'爱　末日曙光　' }, { chord:'G', lyric:'天际沧海' }, { chord:'Am', lyric:'' }],
        [{ chord:'F', lyric:'握紧我　冲破这　自私' }, { chord:'G', lyric:'年代' }],
      ]},
      { title: '尾声', lines: [
        [{ chord:'Am', lyric:'这给你的　世界' }, { chord:'F', lyric:'' }],
        [{ chord:'C', lyric:'破裂不完美　抱歉感慨' }, { chord:'G', lyric:'' }],
        [{ chord:'Am', lyric:'这个世界的未来' }, { chord:'F', lyric:'' }],
        [{ chord:'C', lyric:'是否更惭愧　沮丧的' }, { chord:'G', lyric:'交给你' }],
        [{ chord:'Am', lyric:'亲爱小孩' }],
      ]},
    ],
  },
  // ──────────────────────────────────────────
  {
    id: 'lianfengchen',
    title: '恋恋风尘',
    artist: '老狼',
    baseKey: 'E', playKey: 'C', capo: 4,
    chords: ['C','G','Em','F','Am','G7'],
    sections: [
      { title: '主歌', lines: [
        [{ chord:'C', lyric:'那天黄昏 开始飘起了' }, { chord:'G', lyric:'白雪' }],
        [{ chord:'Em', lyric:'忧伤开满山岗' }, { chord:'F', lyric:'等青春散场' }],
        [{ chord:'C', lyric:'午夜的电影写满古老的' }, { chord:'G', lyric:'恋情' }],
        [{ chord:'F', lyric:'在黑暗中为年轻' }, { chord:'C', lyric:'歌唱' }],
        [{ chord:'C', lyric:'走吧 女孩 去看红色的' }, { chord:'G', lyric:'朝霞' }],
        [{ chord:'Em', lyric:'带上我的恋歌' }, { chord:'F', lyric:'你迎风吟唱' }],
        [{ chord:'C', lyric:'露水挂在发梢 结满透明的' }, { chord:'G', lyric:'惆怅' }],
        [{ chord:'F', lyric:'是我一生最初的' }, { chord:'C', lyric:'迷惘' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'C', lyric:'当岁月和美丽' }, { chord:'F', lyric:'已成风尘中的叹息' }],
        [{ chord:'E', lyric:'' }, { chord:'Am', lyric:'你感伤的眼里有旧时泪滴' }],
        [{ chord:'C', lyric:'相信爱的年纪' }, { chord:'F', lyric:'没能唱给你的歌曲' }],
        [{ chord:'Am', lyric:'' }, { chord:'G7', lyric:'让我一生常常追忆' }],
        [{ chord:'C', lyric:'相信爱的年纪' }, { chord:'F', lyric:'没能唱给你的歌曲' }],
        [{ chord:'Am', lyric:'' }, { chord:'G7', lyric:'让我一生常常追忆' }],
      ]},
      { title: '尾奏', lines: [
        [{ chord:'Am', lyric:' ' }, { chord:'F', lyric:' ' }, { chord:'C', lyric:' ' }],
        [{ chord:'Am', lyric:' ' }, { chord:'F', lyric:' ' }, { chord:'G7', lyric:' ' }, { chord:'C', lyric:' ' }],
      ]},
    ],
  },
  // ──────────────────────────────────────────
  {
    id: 'hongdou',
    title: '红豆',
    artist: '王菲',
    baseKey: 'C', playKey: 'C', capo: 0,
    chords: ['C','G/B','Am','Em','F','Dm','G'],
    sections: [
      { title: '主歌一', lines: [
        [{ chord:'C', lyric:'还没好好的感受' }, { chord:'G/B', lyric:'' }, { chord:'Am', lyric:'雪花绽放的气候' }, { chord:'Em', lyric:'' }],
        [{ chord:'F', lyric:'我们一起颤抖 会更明白' }, { chord:'C', lyric:'' }, { chord:'Dm', lyric:'什么是' }, { chord:'G', lyric:'温柔' }],
        [{ chord:'C', lyric:'还没跟你牵着手' }, { chord:'G/B', lyric:'' }, { chord:'Am', lyric:'走过荒芜的沙丘' }, { chord:'Em', lyric:'' }],
        [{ chord:'F', lyric:'可能从此以后 学会珍惜' }, { chord:'C', lyric:'' }, { chord:'Dm', lyric:'天长和' }, { chord:'G', lyric:'地久' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'C', lyric:'有时候 有时候 我会相信一切有尽头' }, { chord:'G/B', lyric:'' }, { chord:'Am', lyric:'' }, { chord:'Em', lyric:'' }],
        [{ chord:'F', lyric:'相聚离开 都有时候' }, { chord:'C', lyric:'' }, { chord:'Dm', lyric:'没有什么会' }, { chord:'G', lyric:'永垂不朽' }],
        [{ chord:'C', lyric:'可是我 有时候 宁愿选择留恋不放手' }, { chord:'G/B', lyric:'' }, { chord:'Am', lyric:'' }, { chord:'F', lyric:'' }],
        [{ chord:'Em', lyric:'等到风景都看透' }, { chord:'Am', lyric:'' }, { chord:'Dm', lyric:'也许你会陪我' }, { chord:'G', lyric:'看细水长' }, { chord:'C', lyric:'流' }],
      ]},
      { title: '主歌二', lines: [
        [{ chord:'C', lyric:'还没有你把红豆' }, { chord:'G/B', lyric:'' }, { chord:'Am', lyric:'熬成缠绵的伤口' }, { chord:'Em', lyric:'' }],
        [{ chord:'F', lyric:'然后一起分享 会更明白' }, { chord:'C', lyric:'' }, { chord:'Dm', lyric:'相思的' }, { chord:'G', lyric:'哀愁' }],
        [{ chord:'C', lyric:'还没有好的感受' }, { chord:'G/B', lyric:'' }, { chord:'Am', lyric:'醒着亲吻的温柔' }, { chord:'Em', lyric:'' }],
        [{ chord:'F', lyric:'可能在我左右 你才追求' }, { chord:'C', lyric:'' }, { chord:'Dm', lyric:'孤独的' }, { chord:'G', lyric:'自由' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'C', lyric:'有时候 有时候 我会相信一切有尽头' }, { chord:'G/B', lyric:'' }, { chord:'Am', lyric:'' }, { chord:'Em', lyric:'' }],
        [{ chord:'F', lyric:'相聚离开 都有时候' }, { chord:'C', lyric:'' }, { chord:'Dm', lyric:'没有什么会' }, { chord:'G', lyric:'永垂不朽' }],
        [{ chord:'C', lyric:'可是我 有时候 宁愿选择留恋不放手' }, { chord:'G/B', lyric:'' }, { chord:'Am', lyric:'' }, { chord:'F', lyric:'' }],
        [{ chord:'Em', lyric:'等到风景都看透' }, { chord:'Am', lyric:'' }, { chord:'Dm', lyric:'也许你会陪我' }, { chord:'G', lyric:'看细水长' }, { chord:'C', lyric:'流' }],
      ]},
    ],
  },
  // ──────────────────────────────────────────
  {
    id: 'qiufeng',
    title: '秋风',
    artist: '四喜丸子',
    baseKey: 'C', playKey: 'C', capo: 0,
    chords: ['Am','F','C','G'],
    sections: [
      { title: '主歌', lines: [
        [{ chord:'Am', lyric:'我要怎么说' }, { chord:'F', lyric:'你才能在乎我' }],
        [{ chord:'C', lyric:'这秋天的风' }, { chord:'G', lyric:'也把你带远了' }],
        [{ chord:'Am', lyric:'指针一点点的过' }, { chord:'F', lyric:'我们没改变什么' }],
        [{ chord:'C', lyric:'这份寂寞也希望你' }, { chord:'G', lyric:'真的懂我' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'Am', lyric:'要怎么说' }, { chord:'F', lyric:'你才能那样爱我' }],
        [{ chord:'C', lyric:'给我快乐' }, { chord:'G', lyric:'烦忧全部离开我' }],
        [{ chord:'Am', lyric:'你对我说' }, { chord:'F', lyric:'爱到底是什么' }],
        [{ chord:'C', lyric:'是不是一阵秋风' }, { chord:'G', lyric:'吹进你的心窝' }],
      ]},
      { title: '桥段', lines: [
        [{ chord:'Am', lyric:'我不难过' }, { chord:'F', lyric:'我的世界只有你一个' }],
        [{ chord:'C', lyric:'如果你离开我' }, { chord:'G', lyric:'也要好好过' }],
        [{ chord:'Am', lyric:'我不难过' }, { chord:'F', lyric:'我的世界只有你一个' }],
        [{ chord:'C', lyric:'如果你离开我' }, { chord:'G', lyric:'也要好好过' }],
      ]},
      { title: '主歌（复）', lines: [
        [{ chord:'Am', lyric:'我要怎么说' }, { chord:'F', lyric:'你才能在乎我' }],
        [{ chord:'C', lyric:'这秋天的风' }, { chord:'G', lyric:'也把你带远了' }],
      ]},
    ],
  },
  // ──────────────────────────────────────────
  {
    id: 'yuebanyequ',
    title: '月半小夜曲',
    artist: '李克勤',
    baseKey: 'Am', playKey: 'Am', capo: 0,
    chords: ['Am','Dm','G','C','E','F','Em'],
    sections: [
      { title: '主歌', lines: [
        [{ chord:'Am', lyric:'仍然倚在失眠夜' }, { chord:'Dm', lyric:'望天边星宿' }],
        [{ chord:'G', lyric:'仍然听见小提琴如泣似诉' }, { chord:'C', lyric:'再挑' }, { chord:'E', lyric:'逗' }],
        [{ chord:'Am', lyric:'为何只剩一弯月' }, { chord:'Dm', lyric:'留在我的天空' }],
        [{ chord:'F', lyric:'这晚以后音讯' }, { chord:'E', lyric:'隔绝' }],
        [{ chord:'Am', lyric:'人如天上的明月' }, { chord:'Dm', lyric:'是不可拥有' }],
        [{ chord:'G', lyric:'情如曲过只遗留无可挽' }, { chord:'C', lyric:'救再分' }, { chord:'E', lyric:'别' }],
        [{ chord:'Am', lyric:'为何只是失望填密' }, { chord:'Dm', lyric:'我的空虚' }],
        [{ chord:'F', lyric:'这晚夜' }, { chord:'E', lyric:'没有吻' }, { chord:'Am', lyric:'别' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'F', lyric:'仍在说永' }, { chord:'G', lyric:'久想不' }, { chord:'Em', lyric:'到是藉' }, { chord:'Am', lyric:'口' }, { chord:'F', lyric:'从未意' }, { chord:'Dm', lyric:'会要分' }, { chord:'E', lyric:'手' }],
        [{ chord:'Am', lyric:'但我的心每分每刻' }, { chord:'Dm', lyric:'仍然被她占有' }],
        [{ chord:'G', lyric:'她似这月儿仍然是' }, { chord:'C', lyric:'不开' }, { chord:'E', lyric:'口' }],
        [{ chord:'Am', lyric:'提琴独奏独奏着明月' }, { chord:'Dm', lyric:'半倚深秋' }],
        [{ chord:'F', lyric:'我的牵挂' }, { chord:'G', lyric:'我的渴望' }, { chord:'Am', lyric:'直至以后' }],
      ]},
    ],
  },
  // ──────────────────────────────────────────
  {
    id: 'hongsegjx',
    title: '红色高跟鞋',
    artist: '蔡健雅',
    baseKey: 'D', playKey: 'D', capo: 0,
    chords: ['G','A','Bm','D','E7','Gm'],
    sections: [
      { title: '主歌', lines: [
        [{ chord:'G', lyric:'该怎么去形容你最贴切' }, { chord:'A', lyric:'' }, { chord:'Bm', lyric:'拿什么跟你作比较才算特别' }],
        [{ chord:'G', lyric:'对你的感觉　强烈' }, { chord:'A', lyric:'' }, { chord:'D', lyric:'却又不太了解' }, { chord:'Bm', lyric:'' }, { chord:'G', lyric:'只凭' }, { chord:'A', lyric:'直觉' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'G', lyric:'你像窝在　被子里的' }, { chord:'A', lyric:'舒服' }, { chord:'Bm', lyric:'却又像风　捉摸不住' }],
        [{ chord:'G', lyric:'像手腕上散发的' }, { chord:'A', lyric:'香水味　像爱不释手的' }, { chord:'Bm', lyric:'' }],
        [{ chord:'A', lyric:'红色高跟鞋' }],
      ]},
      { title: '主歌', lines: [
        [{ chord:'G', lyric:'该怎么去形容你最贴切' }, { chord:'A', lyric:'' }, { chord:'Bm', lyric:'拿什么跟你作比较才算特别' }],
        [{ chord:'G', lyric:'对你的感觉　强烈' }, { chord:'A', lyric:'' }, { chord:'D', lyric:'却又不太了解' }, { chord:'Bm', lyric:'' }, { chord:'G', lyric:'只凭' }, { chord:'A', lyric:'直觉' }],
      ]},
      { title: '副歌', lines: [
        [{ chord:'G', lyric:'你像窝在　被子里的' }, { chord:'A', lyric:'舒服' }, { chord:'Bm', lyric:'却又像风　捉摸不住' }],
        [{ chord:'G', lyric:'像手腕上散发的' }, { chord:'A', lyric:'香水味　像爱不释手的' }],
        [{ chord:'A', lyric:'红色高跟鞋' }, { chord:'E7', lyric:'' }, { chord:'Gm', lyric:'' }],
      ]},
      { title: '副歌（完整版）', lines: [
        [{ chord:'G', lyric:'你像窝在　被子里的' }, { chord:'A', lyric:'舒服' }, { chord:'Bm', lyric:'却又像风　捉摸不住' }],
        [{ chord:'G', lyric:'像手腕上散发的' }, { chord:'A', lyric:'香水味　像爱不释手的' }],
        [{ chord:'A', lyric:'我爱你有种左灯右行的冲突' }, { chord:'G', lyric:'' }, { chord:'A', lyric:'' }, { chord:'Bm', lyric:'疯狂却怕没有退路' }],
        [{ chord:'G', lyric:'你能否让我停止这种追逐' }, { chord:'A', lyric:'就这么双　最后唯一的' }],
        [{ chord:'A', lyric:'红色高跟鞋' }],
      ]},
    ],
  },
];
